name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Set the branch you want to deploy from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify the version of Node.js

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to Firebase Hosting
      uses: w9jds/firebase-action@v1.5.0
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
